### ISSUE TITLE
Install process indicates issues with node-sass version

### ISSUE THREAD

**Issue by noquierouser** [lyzs90/vuewp#5]
After cloning, I ran `npm install` as instructed, but after a while the install process fails with these messages at the end:

```
4 warnings and 1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/noquierouser/Documents/Proyectos/ptvsite-vue/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Darwin 17.2.0
gyp ERR! command "/usr/local/Cellar/node/10.1.0/bin/node" "/Users/noquierouser/Documents/Proyectos/ptvsite-vue/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/noquierouser/Documents/Proyectos/ptvsite-vue/node_modules/node-sass
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN vuewp@0.0.2 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/noquierouser/.npm/_logs/2018-05-12T20_35_55_752Z-debug.log
```

It seems to be an issue with `node-sass` package, which seems to be a dependency of another package.

Tested with macOS High Sierra and Windows 10 1803.

**Comment by noquierouser** [comment]
As a workaround I ended up installing `node-sass@latest` and `fsevents@latest` manually using `npm install`. This issue is happening because the installer is unable to find `node-sass@4.5.3` required bindings at GitHub, which are solved when installing manually the latest version, same as `fsevents`.

I recommend to check the dependencies for this project and update where possible.
